#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H


/**
 * @file board_config.h
 * @brief Single-file porting layer — all board-specific pin and peripheral
 *        assignments live here.
 *
 * To bring up a new board:
 *  1. Update pin/port macros to match your schematic.
 *  2. Update I2C timing with the value generated by STM32CubeMX for your
 *     target clock and desired I2C frequency.
 *  3. If your board uses an internal oscillator instead of an external
 *     crystal, change BOARD_SYSCLK_SOURCE and update SystemClock_Config()
 *     in board.c to match (oscillator type + USB clock source).
 *
 * Nothing else needs to change — board.c and stm32c0xx_hal_msp.c consume
 * these macros directly.
 */

/* ── Status LED — LED_EN net (PA15 → NPN Q1 → LED1, active HIGH) ─────────── */

#define BOARD_LED_PORT          GPIOA
#define BOARD_LED_PIN           GPIO_PIN_15

/* ── FAN_FORCE_EN push button — SW1 (PC13 → GND, active LOW, 10K pull-up) ── */

#define BOARD_FAN_FORCE_EN_PORT     GPIOC
#define BOARD_FAN_FORCE_EN_PIN      GPIO_PIN_13

/* ── 1-Wire bus (DS18B20) ────────────────────────────────────────────────── */

#define BOARD_ONEWIRE_PORT          GPIOB
#define BOARD_ONEWIRE_PIN           GPIO_PIN_4

/* PB5 → NPN Q2 → DS18B20 VDD supply (active HIGH = sensor powered) */
#define BOARD_ONEWIRE_PWR_EN_PORT   GPIOB
#define BOARD_ONEWIRE_PWR_EN_PIN    GPIO_PIN_5

/* PB8 → NPN Q3 → 1-Wire strong pull-up resistor (active HIGH = enabled) */
#define BOARD_ONEWIRE_PU_EN_PORT    GPIOB
#define BOARD_ONEWIRE_PU_EN_PIN     GPIO_PIN_8

/* ── LCD power enable (PB15 → NPN Q18 → LCD +PWR_OUT, active HIGH) ──────── */

#define BOARD_LCD_PWR_EN_PORT   GPIOB
#define BOARD_LCD_PWR_EN_PIN    GPIO_PIN_15

/* ── I2C sensor bus ──────────────────────────────────────────────────────── */

#define BOARD_I2C_INSTANCE      I2C2
#define BOARD_I2C_TIMING        0x10805D88U   /* 48 MHz PCLK → ~100 kHz (STM32CubeMX) */
#define BOARD_I2C_SDA_PORT      GPIOA
#define BOARD_I2C_SDA_PIN       GPIO_PIN_6
#define BOARD_I2C_SCL_PORT      GPIOA
#define BOARD_I2C_SCL_PIN       GPIO_PIN_7
#define BOARD_I2C_AF            GPIO_AF6_I2C2
#define BOARD_I2C_CLK_ENABLE()  __HAL_RCC_I2C2_CLK_ENABLE()
#define BOARD_I2C_CLK_DISABLE() __HAL_RCC_I2C2_CLK_DISABLE()

/* ── UART1 — debug serial (PB6 TX / PB7 RX) ─────────────────────────────── */

#define BOARD_UART1_INSTANCE    USART1
#define BOARD_UART1_BAUD_RATE   115200U

/* ── System clock source ─────────────────────────────────────────────────── */
/*
 * HSE = 8 MHz external crystal.
 * On the Nucleo, the ST-LINK provides the 8 MHz signal via MCO.
 * On a custom board without an external crystal, change this to
 * RCC_SYSCLKSOURCE_HSI and update SystemClock_Config() in board.c:
 *   - Remove RCC_OSCILLATORTYPE_HSE / HSEState from OscInitStruct
 *   - Enable RCC_OSCILLATORTYPE_HSI / set HSIState = RCC_HSI_ON
 *   - Update USB clock source in HAL_PCD_MspInit (stm32c0xx_hal_msp.c)
 */
#define BOARD_SYSCLK_SOURCE     RCC_SYSCLKSOURCE_HSE

/* ── TIM2 — PWM input capture (CH3 = channel A, CH4 = channel B) ─────────── */

#define BOARD_TIM2_IC_PORT      GPIOB
#define BOARD_TIM2_IC_PINS      (GPIO_PIN_10 | GPIO_PIN_11)
#define BOARD_TIM2_IC_AF        GPIO_AF3_TIM2

/* ── TIM16 — PWM repeater output A ──────────────────────────────────────── */

#define BOARD_TIM16_CH1_PORT    GPIOA
#define BOARD_TIM16_CH1_PIN     GPIO_PIN_0
#define BOARD_TIM16_CH1_AF      GPIO_AF2_TIM16

/* ── TIM17 — PWM repeater output B ──────────────────────────────────────── */

#define BOARD_TIM17_CH1_PORT    GPIOA
#define BOARD_TIM17_CH1_PIN     GPIO_PIN_1
#define BOARD_TIM17_CH1_AF      GPIO_AF2_TIM17

/* ── TIM1 — fan power PWM (4 channels) ──────────────────────────────────── */
/*
 * CH3 → PA2  AF5
 * CH4 → PA3  AF5
 * CH1 → PA8  AF2
 * CH2 → PA9  AF2
 */
#define BOARD_TIM1_CH34_PORT    GPIOA
#define BOARD_TIM1_CH34_PINS    (GPIO_PIN_2 | GPIO_PIN_3)
#define BOARD_TIM1_CH34_AF      GPIO_AF5_TIM1
#define BOARD_TIM1_CH12_PORT    GPIOA
#define BOARD_TIM1_CH12_PINS    (GPIO_PIN_8 | GPIO_PIN_9)
#define BOARD_TIM1_CH12_AF      GPIO_AF2_TIM1

/* ── TIM3 — fan remote/control PWM (4 channels) ──────────────────────────── */
/*
 * CH3 → PB0  AF1
 * CH4 → PB1  AF1
 * CH1 → PC6  AF1
 * CH2 → PB9  AF3
 */
#define BOARD_TIM3_CH34_PORT    GPIOB
#define BOARD_TIM3_CH34_PINS    (GPIO_PIN_0 | GPIO_PIN_1)
#define BOARD_TIM3_CH34_AF      GPIO_AF1_TIM3
#define BOARD_TIM3_CH1_PORT     GPIOC
#define BOARD_TIM3_CH1_PIN      GPIO_PIN_6
#define BOARD_TIM3_CH1_AF       GPIO_AF1_TIM3
#define BOARD_TIM3_CH2_PORT     GPIOB
#define BOARD_TIM3_CH2_PIN      GPIO_PIN_9
#define BOARD_TIM3_CH2_AF       GPIO_AF3_TIM3

/* ── FAN TYPE SELECT DIP switches (one bit per fan unit) ─────────────────── */
/*
 * LOW (switch closed to GND) = 3/4-wire fan
 * HIGH (switch open, pull-up active) = 2-wire fan
 *
 * PD0 = Fan Unit 1, PD1 = Fan Unit 2, PD2 = Fan Unit 3, PD3 = Fan Unit 4
 */
#define BOARD_FAN_TYPE_PORT     GPIOD
#define BOARD_FAN1_TYPE_PIN     GPIO_PIN_0
#define BOARD_FAN2_TYPE_PIN     GPIO_PIN_1
#define BOARD_FAN3_TYPE_PIN     GPIO_PIN_2
#define BOARD_FAN4_TYPE_PIN     GPIO_PIN_3

/* ── FAN TACHO inputs ────────────────────────────────────────────────────── */
#define BOARD_FAN1_TACHO_PORT   GPIOC
#define BOARD_FAN1_TACHO_PIN    GPIO_PIN_7
#define BOARD_FAN2_TACHO_PORT   GPIOB
#define BOARD_FAN2_TACHO_PIN    GPIO_PIN_14
#define BOARD_FAN3_TACHO_PORT   GPIOA
#define BOARD_FAN3_TACHO_PIN    GPIO_PIN_5
#define BOARD_FAN4_TACHO_PORT   GPIOC
#define BOARD_FAN4_TACHO_PIN    GPIO_PIN_15

#endif /* BOARD_CONFIG_H */
